services:
  - type: web
    name: personal-blog-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: GIN_MODE
        value: release
      - key: API_PORT
        value: 9876
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: CORS_ALLOWED_ORIGINS
        sync: false # This will be set in the Render dashboard
      - key: JWT_SECRET
        generateValue: true # Automatically generates a random value
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 168h
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: CREATE_DEFAULT_ADMIN
        value: "true"
      - key: DEFAULT_ADMIN_USERNAME
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false

databases:
  - name: blog-db
    databaseName: blog_db
    user: bloguser
